import AffiliateDisclosure from "@/components/AffiliateDisclosure";
import TopNavigation from "@/components/TopNavigation";
import ProductCard from "@/components/ProductCard";
import LotteryCard from "@/components/genre/LotteryCard";
import RestockCard from "@/components/genre/RestockCard";
import { genreConfigs } from "@/data/genre-config";
import { genres, type LotteryItem, type RankingItem, type RestockItem } from "@/data/types";
import { getGenreContext } from "@/lib/genres";
type Kind="lottery"|"ranking"|"restock";
export default async function CrossGenrePage({kind}:{kind:Kind}){const contexts=await Promise.all(genres.map(g=>getGenreContext(g)));const meta={lottery:["◎","抽選情報","全ジャンルの応募できる抽選と締切をまとめて確認"],ranking:["↗","現在相場","全ジャンルの値動きをまとめてチェック"],restock:["↻","再販情報","全ジャンルの販売予定・再入荷情報をまとめて確認"]}[kind];const lotteryRows=kind==="lottery"?contexts.flatMap(c=>c?c.data.lottery.map(item=>({item,genre:c.config.slug})):[]):[];const rankingRows=kind==="ranking"?contexts.flatMap(c=>c?c.data.ranking.map(item=>({item,genre:c.config.slug})):[]):[];const restockRows=kind==="restock"?contexts.flatMap(c=>c?c.data.restock.map(item=>({item,genre:c.config.slug})):[]):[];const count=lotteryRows.length+rankingRows.length+restockRows.length;return <main className="min-h-screen bg-[#050b18] text-white"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><TopNavigation/><div className="mt-5"><AffiliateDisclosure/></div><header className="mt-8"><p className="text-xs font-black tracking-[.2em] text-blue-400">ALL CATEGORIES</p><h1 className="mt-2 text-3xl font-black">{meta[0]} {meta[1]}</h1><p className="mt-3 text-slate-300">{meta[2]}</p></header><section className="mt-8 space-y-4">{count===0?<div className="rounded-2xl border border-blue-400/20 bg-[#09152c] p-6 text-slate-400">現在掲載中の情報はありません。</div>:kind==="lottery"?lotteryRows.map(({item,genre}:{item:LotteryItem;genre:typeof genres[number]})=><div key={`${genre}-${item.id}`}><p className="mb-2 text-xs font-black text-blue-300">{genreConfigs[genre].name}</p><LotteryCard item={item}/></div>):kind==="restock"?restockRows.map(({item,genre}:{item:RestockItem;genre:typeof genres[number]})=><div key={`${genre}-${item.id}`}><p className="mb-2 text-xs font-black text-blue-300">{genreConfigs[genre].name}</p><RestockCard item={item}/></div>):rankingRows.map(({item,genre}:{item:RankingItem;genre:typeof genres[number]})=><div key={`${genre}-${item.id}`}><p className="mb-2 text-xs font-black text-blue-300">{genreConfigs[genre].name}</p><ProductCard emoji={item.icon} category={item.shop} title={item.product} price={typeof item.currentPrice==="number"?`現在 ${item.currentPrice.toLocaleString()}円 / 前回 ${(item.previousPrice??item.currentPrice).toLocaleString()}円`:item.price} description={item.status} href={item.href}/></div>)}</section></div></main>}
