import type { Metadata } from "next";
import Link from "next/link";
import AffiliateDisclosure from "@/components/AffiliateDisclosure";
import TopNavigation from "@/components/TopNavigation";
import { genres, type LotteryItem } from "@/data/types";
import { getGenreContext } from "@/lib/genres";
export const metadata: Metadata = { title:"今日の注目｜プレミア速報", description:"今日締切の抽選、相場上昇中、新着再販情報を全ジャンル横断で確認。", alternates:{canonical:"/today"} }; export const dynamic="force-dynamic";
const fmt=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"});
function today(item:LotteryItem,key:string){if(item.deadlineAt){const d=new Date(item.deadlineAt);return !Number.isNaN(d.getTime())&&fmt.format(d)===key}return /本日|今日/.test(item.deadline)}
export default async function Today(){const cs=await Promise.all(genres.map(g=>getGenreContext(g)));const ds=cs.flatMap(c=>c?[c.data]:[]);const key=fmt.format(new Date());const counts={lottery:ds.reduce((n,d)=>n+d.lottery.filter(i=>today(i,key)).length,0),ranking:ds.reduce((n,d)=>n+d.ranking.filter(i=>(i.changeAmount??0)>0||(i.changeRate??0)>0).length,0),restock:ds.reduce((n,d)=>n+d.restock.length,0)};const cards=[{href:"/lottery",label:"今日締切の抽選",value:counts.lottery,icon:"◎"},{href:"/ranking",label:"相場上昇中",value:counts.ranking,icon:"↗"},{href:"/restock",label:"新着再販情報",value:counts.restock,icon:"↻"}];return <main className="min-h-screen bg-[#050b18] text-white"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><TopNavigation/><div className="mt-5"><AffiliateDisclosure/></div><header className="mt-8"><p className="text-xs font-black tracking-[.2em] text-blue-400">TODAY&apos;S SIGNAL</p><h1 className="mt-2 text-3xl font-black">今日の注目</h1><p className="mt-3 text-slate-300">いま確認したい情報を、全ジャンルの取得済みデータからまとめています。</p></header><div className="mt-8 grid gap-4 sm:grid-cols-3">{cards.map(c=><Link key={c.href} href={c.href} className="rounded-2xl border border-blue-400/25 bg-[#09152c] p-5 transition hover:border-blue-300"><div className="flex justify-between"><span className="font-bold text-slate-300">{c.label}</span><span className="text-blue-400">{c.icon}</span></div><p className="mt-4 text-4xl font-black text-sky-300">{c.value}<span className="ml-1 text-sm text-slate-400">件</span></p><p className="mt-4 text-sm font-bold text-blue-300">一覧を見る →</p></Link>)}</div></div></main>}
