import type { GenreConfig } from "@/data/genre-config";
import type { Product, ProductCategory, RankingItem } from "@/data/types";
import { compareWithRetailPrice } from "@/lib/product-categories";
import GenrePageFrame from "./GenrePageFrame";
import EmptyState from "./EmptyState";

export default function MarketRankingPage({ config, products, ranking, category }: { config: GenreConfig; products: Product[]; ranking: RankingItem[]; category: ProductCategory }) {
  const collection = category === "collection-box"; const productMap = new Map(products.map((item) => [item.id, item]));
  return <GenrePageFrame config={config}><header className="mt-6"><h1 className="text-3xl font-bold md:text-4xl">{config.name} {collection ? "コレクション相場ランキング" : "BOX相場ランキング"}</h1><p className="mt-3 text-slate-300">安全に同一商品と確認でき、価格取得に成功した商品だけを掲載します。</p><p className="mt-2 text-xs text-slate-400">定価比は現在の市場価格との差を示す参考指標で、購入や利益を保証するものではありません。</p></header><section className="mt-8 space-y-4">{ranking.length === 0 ? <EmptyState message={collection ? "安全に商品を照合できた相場データはまだありません。商品一覧はコレクションBOXから確認できます。" : undefined} /> : ranking.map((item, index) => { const product = productMap.get(item.id); const current = item.currentPrice ?? item.marketPrice; const retail = product?.retailPrice ?? item.retailPrice; const comparison = compareWithRetailPrice(current, retail); return <article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start gap-3"><span className="text-xl font-black text-blue-300">#{index + 1}</span><h2 className="min-w-0 break-words text-lg font-black">{item.product}</h2></div><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="現在相場" value={current ? `${current.toLocaleString()}円` : "確認中"} /><Metric label="定価" value={retail ? `${retail.toLocaleString()}円` : "公式確認なし"} /><Metric label="定価比" value={comparison ? `${comparison.rate >= 0 ? "+" : ""}${comparison.rate.toFixed(1)}%` : "判定なし"} sub={comparison?.label} /><Metric label="前回比" value={typeof item.changeRate === "number" ? `${item.changeRate >= 0 ? "+" : ""}${item.changeRate.toFixed(2)}%` : "比較前"} sub={typeof item.changeAmount === "number" ? `${item.changeAmount >= 0 ? "+" : ""}${item.changeAmount.toLocaleString()}円` : undefined} /></div><p className="mt-4 break-words text-xs text-slate-400">取得先: {item.shop}</p></article>; })}</section></GenrePageFrame>;
}
function Metric({ label, value, sub }: { label: string; value: string; sub?: string }) { return <div className="min-w-0 rounded-xl bg-slate-950 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 break-words font-black text-white">{value}</p>{sub && <p className="mt-1 text-xs text-blue-300">{sub}</p>}</div>; }
